---
pr_list_failed:
  git_hoster:
    # - name: 'github'
    #   api_url: 'https://api.github.com/'
    #   orgs:
    #     - 'opentelekcloud-docs'
    #   repos:
    - name: 'gitea'
      api_url: 'https://api.github.com/'
      orgs:
        - docs
      repos: