---
pr_list_failed:
  git_hoster:
    - name: 'github'
      api_url: 'https://api.github.com/'
      orgs:
        - 'opentelekomcloud-docs'
      repos:
    - name: 'gitea'
      api_url: 'https://gitea.eco.tsi-dev.otc-service.com/api/v1/'
      orgs:
        - docs
      repos: